name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deps
        run: |
          sudo apt-get update &&
          sudo apt-get install -y --no-install-recommends \
            build-essential meson ninja-build

      - name: Configure
        run: meson setup --reconfigure build

      - name: Build
        run: meson compile -C build

      - name: Test
        run: meson test -C build
