name: Icon CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deps
        run: |
          sudo apt-get update &&
          sudo apt-get install -y meson ninja-build inkscape npm &&
          npm install -g svgo

      - name: Configure
        run: meson setup assets/icons/build assets/icons

      - name: Build
        run: meson compile -C assets/icons/build
